### PR TITLE
Development

### PR DESCRIPTION
**Pull request by bellom**
Project completed kindly cross check
Thanks.

### CODE REVIEW

**Review by heyapricot — CHANGES_REQUESTED** [review]
# It exploded💥
Screen Shot 2019-05-15 at 07 51 26

There is an error in the application. Please:
1. Fix
2. Test your projects before submitting them for review. Thanks

**Comment by darshanjayadev** [comment]
@heyapricot
> Screen Shot 2019-05-15 at 07 51 26
> 
> There is an error in the application. Please:
> 
> 1. Fix
> 2. Test your projects before submitting them for review. Thanks

Sorry for that, I'd assume that it is the product of all the changes that `Stickler` "fixed" - which we should not have allowed. And we assure you that we did test it before adding `Stickler`. The errors have been fixed by my fellow coding partner.

Thank you

**Review by heyapricot — APPROVED** [review]
# Nice job completing this project. No need from my side for further review. Let's move to the next project 🚀

**Comment by bellom** [comment]
Thanks

**Pull request merged**
